image: luki42/flutter-rust:linux

stages:
  - build
  - test
  - deploy

# download path for secure gitlab files
variables:
  SECURE_FILES_DOWNLOAD_PATH: './android/'

flutter_build_android:
  stage: build
  image: luki42/flutter-rust:latest
  tags:
    - huge
  before_script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | sh
  script:
    - make apk
  artifacts:
    expire_in: 5 days
    paths:
      - build/app/outputs/apk/release/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

flutter_build_linux:
  stage: build
  script:
    - make linux
  artifacts:
    expire_in: 5 days
    paths:
      - build/linux/x64/release/bundle/*

android_deploy:
  stage: deploy
  image: luki42/fastlane
  needs:
    - flutter_build_android
  only:
    - main
  before_script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | sh
  script:
    - make deploy

android_elevate_production:
  stage: deploy
  image: luki42/fastlane
  only:
    - tags
  needs:
    - flutter_build_android
  before_script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | sh
  script:
    - make elevate


flutter_format:
  stage: test
  script:
    - flutter format . --output none --set-exit-if-changed
  needs: []

flutter_lint:
  stage: test
  script:
    - make translation
    - flutter analyze ./lib
  needs: []

rust_lint:
  stage: test
  script:
    - cd native && cargo clippy
  needs: []

rust_format:
  stage: test
  script:
    - cd native && cargo fmt --check
  needs: []

flutter_test:
  stage: test
  needs: []
  script:
    - flutter pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter test --machine | tojunit -o report.xml
  artifacts:
    when: always
    reports:
      junit:
        - report.xml