name: wormhole
description: A magic-wormhole client
version: 1.1.0
publish_to: 'none'

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # flutter rust interop
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.63.1
  meta: ^1.9.1
  freezed_annotation: ^2.2.0

  # file chooser / open / share
  file_picker: ^5.2.6
  path_provider: ^2.0.13
  share_plus: ^7.0.0
  open_filex: 4.3.2

  # qr scanner/generation
  barcode_widget: 2.0.3

  provider: 6.0.5 # easy wrapper for changenotifier
  shared_preferences: ^2.0.18 # store key/value pairs on disk
  share_handler: 0.0.16 # receive share intents from other apps
  vibration: ^1.7.7 # trigger phone vibrations
  intl: ^0.18.0 # handle translations
  fluttertoast: ^8.2.1 # fancy toast popups
  toggle_switch: ^2.0.1
  permission_handler: ^10.2.0
  url_launcher: ^6.1.9

  # use custom plugin for handling programmatically close of app
  flutter_close_app:
    git:
      url: https://gitlab.com/lukas-heiligenbrunner/fluttercloseapp.git
      ref: master
  flutter_zxing: ^1.1.2
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^7.2.4
  flutter_launcher_icons:
  build_runner:
  freezed: ^2.3.2

# The following section is specific to Flutter packages.
flutter:
  # auto generate translations
  generate: true

  # include material icons
  uses-material-design: true

# app icon generation
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "bitmap.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
